# Generated by Django 4.2.4 on 2023-08-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NiftyData',
        ),
    ]
